# Generated by Django 3.0.5 on 2020-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_auto_20200806_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='desc',
            new_name='quote',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='autor',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
