# Generated by Django 3.0.5 on 2020-08-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_auto_20200812_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='desc',
            new_name='quote',
        ),
    ]
