# Generated by Django 3.0.5 on 2020-08-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_auto_20200813_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill_desc',
            old_name='desc',
            new_name='longdesc',
        ),
        migrations.AddField(
            model_name='advert',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill_desc',
            name='shortdesc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
