# Generated by Django 3.0.5 on 2020-08-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_auto_20200813_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='education',
            name='adress',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employment',
            name='adress',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='employment',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='EmploymentPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.Employment')),
            ],
        ),
    ]
